INSERT INTO :materialdb.material(name, description, density, tensile_strength, elastic_modulus, price, category, applications)
VALUES
('Aluminium 6061', 'Leichte Aluminiumlegierung mit guter Korrosionsbeständigkeit', '2.7 g/cm³', '310 MPa', '68.9 GPa', '3.50 €/kg', 'Metall', 'Flugzeugbau, Fahrradrahmen, Maschinenbau, Elektronikgehäuse'),
('Baustahl S235', 'Standard-Konstruktionsstahl mit guter Schweißbarkeit', '7.85 g/cm³', '360 MPa', '210 GPa', '0.95 €/kg', 'Metall', 'Hochbau, Brückenbau, Stahlkonstruktionen, Maschinenbau'),
('Edelstahl 304', 'Rostfreier austenitischer Stahl mit guter Korrosionsbeständigkeit', '8.0 g/cm³', '505 MPa', '193 GPa', '4.20 €/kg', 'Metall', 'Küchengeräte, Chemische Industrie, Medizintechnik, Lebensmittelindustrie'),
('Titan Grade 5', 'Hochfeste Titanlegierung (Ti-6Al-4V) für Luft- und Raumfahrt', '4.43 g/cm³', '950 MPa', '113.8 GPa', '35.00 €/kg', 'Metall', 'Luft- und Raumfahrt, Medizinische Implantate, Sportgeräte, Automobilindustrie'),
('Kupfer C11000', 'Elektrolytisch reines Kupfer mit hoher elektrischer Leitfähigkeit', '8.96 g/cm³', '220 MPa', '117 GPa', '8.75 €/kg', 'Metall', 'Elektroinstallationen, Rohrleitungen, Wärmetauscher, Elektronik'),
('PLA', 'Biologisch abbaubarer Kunststoff für 3D-Druck', '1.24 g/cm³', '50 MPa', '3.5 GPa', '20.00 €/kg', 'Kunststoff', '3D-Druck, Prototyping, Verpackungen, Spielzeug'),
('Kohlefaser-Verbundwerkstoff', 'Hochfestes Verbundmaterial mit geringem Gewicht', '1.6 g/cm³', '3500 MPa', '230 GPa', '100.00 €/kg', 'Verbundwerkstoff', 'Automobilbau, Luft- und Raumfahrt, Sportgeräte, Windenergie'),
('Glas (Borosilikat)', 'Temperaturbeständiges Glas für Labor- und Küchenanwendungen', '2.23 g/cm³', '30 MPa', '63 GPa', '5.50 €/kg', 'Keramik', 'Laborgeräte, Kochgeschirr, Optik, Chemische Industrie'),
('Eichenholz', 'Robustes Hartholz für Möbel und Konstruktionen', '0.75 g/cm³', '90 MPa', '11 GPa', '2.80 €/kg', 'Holz', 'Möbelbau, Parkett, Fässer, Konstruktionsholz'),
('Beton C30/37', 'Standardbeton für Konstruktionsanwendungen', '2.4 g/cm³', '3.5 MPa', '30 GPa', '0.12 €/kg', 'Baustoff', 'Hochbau, Tiefbau, Fundamente, Straßenbau'),
('ABS', 'Schlagzäher Thermoplast mit guter Verarbeitbarkeit', '1.05 g/cm³', '40 MPa', '2.3 GPa', '2.50 €/kg', 'Kunststoff', '3D-Druck, Gehäuse, Spielzeug, Automobilteile'),
('Magnesium AZ31', 'Leichte Magnesiumlegierung mit guter Bearbeitbarkeit', '1.78 g/cm³', '260 MPa', '45 GPa', '12.00 €/kg', 'Metall', 'Automobilindustrie, Elektronikgehäuse, Luft- und Raumfahrt'),
('Polycarbonat', 'Transparenter, schlagzäher Kunststoff', '1.20 g/cm³', '65 MPa', '2.4 GPa', '4.80 €/kg', 'Kunststoff', 'Schutzscheiben, Optik, Medizintechnik, Elektronik'),
('Messing CuZn37', 'Korrosionsbeständige Kupfer-Zink-Legierung', '8.5 g/cm³', '380 MPa', '100 GPa', '6.20 €/kg', 'Metall', 'Armaturen, Musikinstrumente, Schrauben, Dekorative Anwendungen'),
('PTFE (Teflon)', 'Chemisch inerter Fluorkunststoff mit niedrigem Reibungskoeffizienten', '2.17 g/cm³', '27 MPa', '0.5 GPa', '15.00 €/kg', 'Kunststoff', 'Dichtungen, Beschichtungen, Chemische Industrie, Kochgeschirr'),
('Buchenholz', 'Hartes europäisches Laubholz mit gleichmäßiger Struktur', '0.72 g/cm³', '120 MPa', '14 GPa', '1.20 €/kg', 'Holz', 'Möbelbau, Werkzeugstiele, Spielzeug, Treppen'),
('Zink', 'Korrosionsbeständiges Metall für Beschichtungen', '7.14 g/cm³', '37 MPa', '108 GPa', '2.80 €/kg', 'Metall', 'Verzinkung, Dacheindeckung, Batterien, Gießerei'),
('Nylon 6.6', 'Hochfester technischer Kunststoff', '1.14 g/cm³', '83 MPa', '2.8 GPa', '3.20 €/kg', 'Kunststoff', 'Zahnräder, Lager, Textilien, Automobilteile'),
('Silikon', 'Flexibler, temperaturbeständiger Elastomer', '1.20 g/cm³', '7 MPa', '0.002 GPa', '8.50 €/kg', 'Kunststoff', 'Dichtungen, Medizintechnik, Küchengeräte, Isolierung'),
('Keramik Al2O3', 'Hochtemperaturbeständige technische Keramik', '3.95 g/cm³', '300 MPa', '370 GPa', '25.00 €/kg', 'Keramik', 'Schneidwerkzeuge, Isolatoren, Hochtemperaturanwendungen, Medizintechnik'),
('Epoxidharz', 'Duroplastischer Kunststoff mit hoher Festigkeit', '1.25 g/cm³', '80 MPa', '3.2 GPa', '6.50 €/kg', 'Kunststoff', 'Verbundwerkstoffe, Beschichtungen, Elektronik, Klebstoffe'),
('Inconel 718', 'Hochtemperatur-Superlegierung auf Nickelbasis', '8.22 g/cm³', '1275 MPa', '200 GPa', '45.00 €/kg', 'Metall', 'Gasturbinen, Luft- und Raumfahrt, Chemische Industrie, Hochtemperaturanwendungen'),
('Bambus', 'Nachhaltiges, schnell wachsendes Naturmaterial', '0.60 g/cm³', '140 MPa', '20 GPa', '3.50 €/kg', 'Baumaterial', 'Möbelbau, Konstruktion, Textilien, Papierherstellung'),
('Wolfram', 'Hochschmelzendes Metall mit hoher Dichte', '19.25 g/cm³', '550 MPa', '411 GPa', '35.00 €/kg', 'Metall', 'Glühfäden, Schweißelektroden, Röntgentechnik, Militärtechnik'),
('PEEK', 'Hochleistungs-Thermoplast mit chemischer Beständigkeit', '1.32 g/cm³', '100 MPa', '3.6 GPa', '80.00 €/kg', 'Kunststoff', 'Medizintechnik, Luft- und Raumfahrt, Chemische Industrie, Hochtemperaturanwendungen');